# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/enjolras/platform/dama/player-c_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/enjolras/platform/dama/player-c_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/enjolras/platform/dama/player-c_cpp/CMakeFiles /home/enjolras/platform/dama/player-c_cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/enjolras/platform/dama/player-c_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main_release

# Build rule for target.
main_release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main_release
.PHONY : main_release

# fast build rule for target.
main_release/fast:
	$(MAKE) -f CMakeFiles/main_release.dir/build.make CMakeFiles/main_release.dir/build
.PHONY : main_release/fast

#=============================================================================
# Target rules for targets named main_debug

# Build rule for target.
main_debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main_debug
.PHONY : main_debug

# fast build rule for target.
main_debug/fast:
	$(MAKE) -f CMakeFiles/main_debug.dir/build.make CMakeFiles/main_debug.dir/build
.PHONY : main_debug/fast

local_battle.o: local_battle.cpp.o

.PHONY : local_battle.o

# target to build an object file
local_battle.cpp.o:
	$(MAKE) -f CMakeFiles/main_release.dir/build.make CMakeFiles/main_release.dir/local_battle.cpp.o
	$(MAKE) -f CMakeFiles/main_debug.dir/build.make CMakeFiles/main_debug.dir/local_battle.cpp.o
.PHONY : local_battle.cpp.o

local_battle.i: local_battle.cpp.i

.PHONY : local_battle.i

# target to preprocess a source file
local_battle.cpp.i:
	$(MAKE) -f CMakeFiles/main_release.dir/build.make CMakeFiles/main_release.dir/local_battle.cpp.i
	$(MAKE) -f CMakeFiles/main_debug.dir/build.make CMakeFiles/main_debug.dir/local_battle.cpp.i
.PHONY : local_battle.cpp.i

local_battle.s: local_battle.cpp.s

.PHONY : local_battle.s

# target to generate assembly for a file
local_battle.cpp.s:
	$(MAKE) -f CMakeFiles/main_release.dir/build.make CMakeFiles/main_release.dir/local_battle.cpp.s
	$(MAKE) -f CMakeFiles/main_debug.dir/build.make CMakeFiles/main_debug.dir/local_battle.cpp.s
.PHONY : local_battle.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main_release.dir/build.make CMakeFiles/main_release.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/main_debug.dir/build.make CMakeFiles/main_debug.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main_release.dir/build.make CMakeFiles/main_release.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/main_debug.dir/build.make CMakeFiles/main_debug.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main_release.dir/build.make CMakeFiles/main_release.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/main_debug.dir/build.make CMakeFiles/main_debug.dir/main.cpp.s
.PHONY : main.cpp.s

my_sol.o: my_sol.cpp.o

.PHONY : my_sol.o

# target to build an object file
my_sol.cpp.o:
	$(MAKE) -f CMakeFiles/main_release.dir/build.make CMakeFiles/main_release.dir/my_sol.cpp.o
	$(MAKE) -f CMakeFiles/main_debug.dir/build.make CMakeFiles/main_debug.dir/my_sol.cpp.o
.PHONY : my_sol.cpp.o

my_sol.i: my_sol.cpp.i

.PHONY : my_sol.i

# target to preprocess a source file
my_sol.cpp.i:
	$(MAKE) -f CMakeFiles/main_release.dir/build.make CMakeFiles/main_release.dir/my_sol.cpp.i
	$(MAKE) -f CMakeFiles/main_debug.dir/build.make CMakeFiles/main_debug.dir/my_sol.cpp.i
.PHONY : my_sol.cpp.i

my_sol.s: my_sol.cpp.s

.PHONY : my_sol.s

# target to generate assembly for a file
my_sol.cpp.s:
	$(MAKE) -f CMakeFiles/main_release.dir/build.make CMakeFiles/main_release.dir/my_sol.cpp.s
	$(MAKE) -f CMakeFiles/main_debug.dir/build.make CMakeFiles/main_debug.dir/my_sol.cpp.s
.PHONY : my_sol.cpp.s

solution.o: solution.cpp.o

.PHONY : solution.o

# target to build an object file
solution.cpp.o:
	$(MAKE) -f CMakeFiles/main_release.dir/build.make CMakeFiles/main_release.dir/solution.cpp.o
	$(MAKE) -f CMakeFiles/main_debug.dir/build.make CMakeFiles/main_debug.dir/solution.cpp.o
.PHONY : solution.cpp.o

solution.i: solution.cpp.i

.PHONY : solution.i

# target to preprocess a source file
solution.cpp.i:
	$(MAKE) -f CMakeFiles/main_release.dir/build.make CMakeFiles/main_release.dir/solution.cpp.i
	$(MAKE) -f CMakeFiles/main_debug.dir/build.make CMakeFiles/main_debug.dir/solution.cpp.i
.PHONY : solution.cpp.i

solution.s: solution.cpp.s

.PHONY : solution.s

# target to generate assembly for a file
solution.cpp.s:
	$(MAKE) -f CMakeFiles/main_release.dir/build.make CMakeFiles/main_release.dir/solution.cpp.s
	$(MAKE) -f CMakeFiles/main_debug.dir/build.make CMakeFiles/main_debug.dir/solution.cpp.s
.PHONY : solution.cpp.s

unit_test.o: unit_test.cpp.o

.PHONY : unit_test.o

# target to build an object file
unit_test.cpp.o:
	$(MAKE) -f CMakeFiles/main_release.dir/build.make CMakeFiles/main_release.dir/unit_test.cpp.o
	$(MAKE) -f CMakeFiles/main_debug.dir/build.make CMakeFiles/main_debug.dir/unit_test.cpp.o
.PHONY : unit_test.cpp.o

unit_test.i: unit_test.cpp.i

.PHONY : unit_test.i

# target to preprocess a source file
unit_test.cpp.i:
	$(MAKE) -f CMakeFiles/main_release.dir/build.make CMakeFiles/main_release.dir/unit_test.cpp.i
	$(MAKE) -f CMakeFiles/main_debug.dir/build.make CMakeFiles/main_debug.dir/unit_test.cpp.i
.PHONY : unit_test.cpp.i

unit_test.s: unit_test.cpp.s

.PHONY : unit_test.s

# target to generate assembly for a file
unit_test.cpp.s:
	$(MAKE) -f CMakeFiles/main_release.dir/build.make CMakeFiles/main_release.dir/unit_test.cpp.s
	$(MAKE) -f CMakeFiles/main_debug.dir/build.make CMakeFiles/main_debug.dir/unit_test.cpp.s
.PHONY : unit_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main_release"
	@echo "... main_debug"
	@echo "... local_battle.o"
	@echo "... local_battle.i"
	@echo "... local_battle.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... my_sol.o"
	@echo "... my_sol.i"
	@echo "... my_sol.s"
	@echo "... solution.o"
	@echo "... solution.i"
	@echo "... solution.s"
	@echo "... unit_test.o"
	@echo "... unit_test.i"
	@echo "... unit_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

